---
    - hosts: client
      tasks:
        - name: Install and Configure OpenSSH Server
          script: /home/team3user/packer-deployment/packer_templates/windows/scripts/install_openssh.ps1
        - name: Set internal DNS server 
          win_dns_client:
            adapter_names: '*'
            ipv4_addresses:
              - '10.242.43.253'
        - name: Join Domain
          win_domain_membership:
            dns_domain_name: starkindustries.marvel.com
            domain_admin_user: starkindustries\stark
            domain_admin_password: QR<cwC6piashc4
            state: domain
          register: domain
        - name: Reboot if installing domain joining requires it
          win_reboot:
          when: domain.reboot_required