---
    - hosts: client
      tasks:
        - name: Install and Configure OpenSSH Server
          script: /home/team3user/packer-deployment/packer_templates/windows/scripts/install_openssh.ps1
        - name: Set internal DNS server
          win_dns_client:
            adapter_names: '*'
            ipv4_addresses:
              - '10.242.43.253'
        - name: Join Domain
          win_domain_membership:
            dns_domain_name: starkindustries.marvel.com
            domain_admin_user: starkindustries\stark
            domain_admin_password: QR<cwC6piashc4
            state: domain
          register: domain
        - name: Include Firewall rule to allow Web Server access
          win_firewall_rule:
            name: Web Server
            localport: any
            remoteip: 192.168.57.1-192.168.57.254
            action: allow
            protocol: any
        - name: Reboot if installing domain joining requires it
          win_reboot:
          when: domain.reboot_required
        - name: Enable Public Key Authentication for SSH
          win_lineinfile:
            path: c:\program files\openssh\sshd_config_default
            regexp: '^(.*)PubkeyAuthentication(.*)$'
            line: PubkeyAuthentication yes
            backrefs: yes
        - name: Enable Password Authentication for SSH
          win_lineinfile:
            path: c:\program files\openssh\sshd_config_default
            regexp: '^(.*)PasswordAuthentication(.*)$'
            line: PasswordAuthentication yes
            backrefs: yes
        