---
    - hosts: dhcp
      vars:
        dhcp_address: "10.242.43.252"
        dhcp_gateway: "10.242.43.254"
        dhcp_dns: "10.242.43.253"
      tasks:
      - name: Set internal DNS server 
        win_dns_client:
          adapter_names: '*'
          ipv4_addresses:
            - '10.242.43.253'
      - name: Set Default Gateway
        win_shell: win_shell: netsh interface ipv4 set address name="Ethernet 2" static {{dhcp_address}} 255.255.255.0 {{dhcp_gateway}}
        ignore_unreachable: yes
      - name: Join Domain
        win_domain_membership:
          dns_domain_name: starkindustries.marvel.com
          hostname: DHCP1
          domain_admin_user: starkindustries\stark
          domain_admin_password: QR<cwC6piashc4
          state: domain
      - name: Install DHCP Server
        win_feature:
          name: DHCP
          include_management_tools: yes
          include_sub_features: yes
          state: present
        register: dhcp
      - name: Reboot if installing DHCP feature requires it
        win_reboot:
        when: dhcp.reboot_required
      - name: Implement Security Groups to DHCP
        win_shell: netsh dhcp add securitygroups
      - name: Restart DHCP Services
        win_shell: Restart-Service dhcpserver
      - name: Authorise DHCP Server to the AD
        win_shell: Add-DhcpServerInDC -DnsName DHCP1.starkindustries.marvel.com -IPAddress 10.242.43.252
        vars:
          ansible_become: true
          ansible_become_method: runas
          ansible_become_user: starkindustries\stark
          ansible_become_password: QR<cwC6piashc4
      - name: Notify Server Manager that post-install DHCP configuration is completed
        win_shell: Set-ItemProperty –Path registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ServerManager\Roles\12 –Name ConfigurationState –Value 2
      - name: Setup a DHCP scope
        win_shell: |
          Add-DhcpServerv4Scope -name "Engineering" -StartRange 10.242.43.1 -EndRange 10.242.43.253 -SubnetMask 255.255.255.0 -State Active
          Add-DhcpServerv4ExclusionRange -ScopeID 10.242.43.0 -StartRange 10.242.43.240 -EndRange 10.242.43.253
          Set-DhcpServerv4OptionValue -OptionID 3 -Value {{dhcp_gateway}} -ScopeID 10.242.43.0 -ComputerName DHCP1.starkindustries.marvel.com
          Set-DhcpServerv4OptionValue -DnsDomain starkindustries.marvel.com -DnsServer 10.242.43.253
          Add-DhcpServerv4Filter -List Deny -MacAddress "08-00-27-07-B9-5E" -Description "Web Server"