---
      hosts: all
      tasks:
        - name: Install DHCP Server
          win_feature: >
            name=DhcpServer
            include_management_tools=yes
            include_sub_features=yes
            state=present
        - name: Create Domain
          win_domain: >
            dns_domain_name='{{ domain_name }}'
            safe_mode_password='{{ recovery_password }}'