---
    tasks:
    - name: Disable firewall for Domain, Public and Private profiles
      win_firewall:
        state: disabled
        profiles:
            - Domain
            - Private
            - Public