---
    - name: Install new Active-Directory Domain & Forest
      hosts: all
      vars:
        dc_address: '10.242.43.253'
        dc_hostname: 'DC1'
        domain_name: 'starkindustries.marvel.com'
        local_admin: '.\administrator'
        dc_password: 'vagrant'
        recovery_password: 'SafeModePassw0rd!'
        reverse_dns_zone: "10.242.43.0/24"
      tasks:
        - name: Change the hostname 
          win_hostname:
            name: '{{ dc_hostname }}'
          register: res
        - name: Reboot
          win_reboot:
        - name: Install Active Directory
          win_feature: >
            name=AD-Domain-Services
            include_management_tools=yes
            include_sub_features=yes
            state=present
        - name: Create Domain
          win_domain: >
            dns_domain_name='{{ domain_name }}'
            domain_mode=Win2012R2
            safe_mode_password='{{ recovery_password }}'
        - name: Set internal DNS server 
          win_dns_client:
            adapter_names: '*'
            ipv4_addresses:
            - '127.0.0.1'