---
    - name: Setup and Install new Active-Directory Domain & Forest
      hosts: dc
      vars:
        dc_address: 10.242.43.253
        domain_name: 'starkindustries.marvel.com'
        recovery_password: 'SafeModePassw0rd!'
        reverse_dns_zone: "10.242.43.0/24"
      tasks:
        - name: Set Internal DNS server 
          win_dns_client:
            adapter_names: '*'
            ipv4_addresses:
              - '127.0.0.1'
          async: 30
          poll: 0
        - name: Disable firewall for Domain, Public and Private profiles
          win_firewall:
            state: disabled
            profiles:
              - Domain
              - Private
              - Public
        - name: Install Active Directory
          win_feature:
            name: AD-Domain-Services
            include_management_tools: yes
            include_sub_features: yes
            state: present
        - name:
          win_domain:
            domain_mode: Win2012R2 
            dns_domain_name: '{{ domain_name }}'
            safe_mode_password: '{{ recovery_password }}'
          register: ad
        - name: Reboot server
          win_reboot:
            msg: "Installing AD. Rebooting..."
            pre_reboot_delay: 15
          when: ad.changed
        - name: Domain Account Creation
          win_domain_user:
            surname: "{{ item.surname }}"
            firstname: "{{ item.firstname }}"
            company: Stark Industries
            groups: "{{ item.groups }}"
            name: "{{ item.name }}"
            password: "{{ item.password }}"
            password_never_expires: yes
            async: 180
            poll: 0
          with_items:
            - surname: Rhodes
              firstname: James
              groups:
                - Domain Users
              name: stark
              password: AVeryS3curePassw0rd!
            - surname: Edward
              firstname: Stark
              groups:
                - Domain Admins
              name: stark
              password: QR<cwC6piashc4
        - name: Create reverse DNS zone
          win_shell: "Add-DnsServerPrimaryZone -NetworkID {{reverse_dns_zone}} -ReplicationScope Forest"    
          retries: 30
          delay: 60
          register: result           
          until: result is succeeded
        - name: Create DNS records
          win_dns_record:
            name: "{{ item.name }}"
            type: "{{ item.type }}"
            value: "{{ item.value }}"
            zone: "{{ item.zone }}"
          async: 180
          poll: 0
          with_items:
            - name: "10.242.43.253"
              type: "PTR"
              value: "dc1"
              zone: "43.242.10.in-addr.arpa"
            - name: "10.242.43.252"
              type: "PTR"
              value: "dhcp1"
              zone: "43.242.10.in-addr.arpa"
            - name: "dhcp1"
              type: "A"
              value: "10.242.43.252"
              zone: "starkindustries.marvel.com"
            