---
    - name: Setup and Install new Active-Directory Domain & Forest
      hosts: dc
      vars:
        dc_address: 10.242.43.253
        dc_netmask_cidr: 24
        dc_gateway: 10.242.43.254
        domain_name: 'starkindustries.marvel.com'
        local_admin: '.\administrator'
        dc_password: 'vagrant'
        recovery_password: 'SafeModePassw0rd!'
        reverse_dns_zone: "10.242.43.0/24"
      tasks:
        - name: Set internal DNS server 
          win_dns_client:
            adapter_names: '*'
            ipv4_addresses:
              - '127.0.0.1'
        - name: Disable firewall for Domain, Public and Private profiles
          win_firewall:
            state: disabled
            profiles:
              - Domain
              - Private
              - Public
        - name: Install Active Directory
          win_feature: >
            name=AD-Domain-Services
            include_management_tools=yes
            include_sub_features=yes
            state=present
        - name: Create Domain
          win_domain: >
            dns_domain_name='{{ domain_name }}'
            domain_mode=Win2012R2
            safe_mode_password='{{ recovery_password }}'
          register: ad
        - name: Reboot server
          win_reboot:
            msg: "Installing AD. Rebooting..."
            pre_reboot_delay: 15
          when: ad.changed
        - name: Create reverse DNS zone
          win_shell: "Add-DnsServerPrimaryZone -NetworkID {{reverse_dns_zone}} -ReplicationScope Forest"    
          retries: 30
          delay: 60
          register: result           
          until: result is succeeded