---
  - name: Setup new Active-Directory Domain & Forest
    hosts: all
    vars:
      dc_address: 10.242.43.253
      dc_netmask_cidr: 24
      dc_gateway: 10.242.43.254
    tasks:
      - name: Set static IP address
        win_shell: "Get-NetIpAddress -InterfaceAlias 'Ethernet' | New-NetIpAddress -IpAddress {{ dc_address }} -PrefixLength {{ dc_netmask_cidr }} -DefaultGateway {{ dc_gateway }}"
        async: 100
        poll: 0
        ignore_errors: True
      - name: Add host to Ansible inventory with new Password
        add_host:
          name: "{{ dc_address }}"
          ansible_connection: winrm
          ansible_winrm_server_cert_validation: ignore
      - name: Wait for system to become reachable over WinRM
        wait_for_connection:
          timeout: 900
      - name: Disable firewall for Domain, Public and Private profiles
        win_firewall:
          state: disabled
          profiles:
          - Domain
          - Private
          - Public
        tags: disable_firewall
        delegate_to: '{{ dc_address }}'
    