---
  - name: Setup new Active-Directory Domain & Forest
    hosts: all
    vars:
      dc_address: 10.242.43.253
      dc_netmask_cidr: 24
      dc_gateway: 10.242.43.254
    tasks:
      - name: Set static IP address
        win_shell: "Get-NetIpAddress -InterfaceAlias 'Ethernet' | New-NetIpAddress -IpAddress {{ dc_address }} -PrefixLength {{ dc_netmask_cidr }} -DefaultGateway {{ dc_gateway }}"
      - name: Disable firewall for Domain, Public and Private profiles
        win_firewall:
          state: disabled
          profiles:
            - Domain
            - Private
            - Public
      
    